[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
monitor_port = /dev/cu.usbserial-0001
monitor_dtr = 0
monitor_rts = 0
monitor_filters = direct
upload_speed = 115200
upload_port = /dev/cu.usbserial-0001
upload_resetmethod = nodemcu

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.0
